import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import React from 'react';

import './globals.css';
import { CloudflareWebAnalytics } from '$/components/CloudflareWebAnalytics/CloudflareWebAnalytics';
import Footer from '$/components/Footer';
import Header from '$/components/Header';
import Main from '$/components/Main';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </ThemeProvider>
        <CloudflareWebAnalytics />
      </body>
    </html>
  );
}
